import Header from "@/containers/header";
import "./globals.css";

export const metadata = {
  title: "반응형 웹 연습",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8"></meta>
        <meta
          httpEquiv="X-UA-Compatible"
          content="IE=edge"
        ></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
      </head>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
